### ISSUE TITLE
Cater for mods that have redundant top-level folders

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/game-starfield#14]
Some mods are packed with top-level folders that aren't necessary. We should see if we can detect/remove these during the installation. 

- Black Pacifier ( https://www.nexusmods.com/starfield/mods/2374 )  
- dp starfield eye material fix ( https://www.nexusmods.com/starfield/mods/1458 )  
- dp scorch marks 2k ( https://www.nexusmods.com/starfield/mods/1124 )  
- Immersive Coffee Mug Graphic Replacer ( https://www.nexusmods.com/starfield/mods/3088 )  
- UC Retexture Project ( https://www.nexusmods.com/starfield/mods/2846 )  
- White Jumpsuit Set  ( https://www.nexusmods.com/starfield/mods/2955 )

**Comment by insomnious** [comment]
Fixed in https://github.com/Nexus-Mods/game-starfield/commit/b80cef4494adbaedda76c671dd6e6b5615ac38c7
