### ISSUE TITLE
Remove case-sensitivity on INI keys

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/game-starfield#23]
The INI checks rely on an exact case match for INI keys. 

A popular mod https://www.nexusmods.com/starfield/mods/3424 sets `SResourceDataDirsFinal ` with a capital S (which does not follow the standard but appears to still be loaded by the game). This prompts Vortex to correct it each time the test runs

**Comment by IDCs** [comment]
As you said, the mod is not following the standard and will not be added to the extension. It's the mod authors job to fix it on his end.
