### ISSUE TITLE
Add a notification for when Data folder exists in My Games

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/game-starfield#24]
If the user is not using a folder junction but still has a Data folder in My Games, this has the potential to silently block mods loading from the game Data folder.

We could warn the user with a notification/dialog that the Vortex pattern of modding Starfield is game Data folder only and they should delete the My Games Data folder. This could be a sort of fallback for those that can't or won't use a folder junction. 

Could warn on game launch, or on deploy.

**Comment by IDCs** [comment]
done in https://github.com/Nexus-Mods/game-starfield/commit/b47330a76302496029b165b54b97055de76efb98
