### ISSUE TITLE
Deploy .TXT files to the Data folder

### ISSUE THREAD

**Issue by lllIIIlll** [Nexus-Mods/game-starfield#28]
Currently, Vortex deploys the TXT files to the Root folder while MO2 deploys them to the Data folder, requiring modders to write two separate instructions, so it would be nice and unified if Vortex also deploys the TXT files to the Data folder.

**Comment by Pickysaurus** [comment]
Why would you want those in the data folder? They aren't data files therefore MO2 is doing it wrong.

**Comment by IDCs** [comment]
@Rando456 - Pickysaurus is right - additionally, there are plenty of mods out there which distribute TXT files meant to be executed through the game's console. For those to work, the TXT files need to be deployed to the game's root folder!

Can you give me an example of a TXT file you'd like to be placed in the data folder and explain why it's required?

**Comment by Pickysaurus** [comment]
They absolutely do not need to be in the Data folder. Console command TXT files should be loaded from the game root by default. You have to go out of your way to misconfigure it.

**Comment by lllIIIlll** [comment]
> there are plenty of mods out there which distribute TXT files meant to be executed through the game's console. For those to work, the TXT files need to be deployed to the game's root folder!

That's a fair point.

> Can you give me an example of a TXT file you'd like to be placed in the data folder and explain why it's required?

I found that the authors of these mods recommend placing the TXT file in the Data folder.
https://www.nexusmods.com/starfield/mods/759
https://www.nexusmods.com/starfield/mods/2210

While TXT files don't technically need to be in the data folder, I think TXT mods that use SetGameSetting and require editing the sStartingConsoleCommand entry are better placed in the Data folder.

**Comment by v2sCollections** [comment]
Joining the conversation. Why would they be better in the data folder if they edit the ini? I can't see the difference and we are talking about a handful of mod authors that have instructed users to place it in the data folder. We need authors to all be on the same page and right now the main method of the root folder is wide spread on nexus.

**Comment by lllIIIlll** [comment]
> Why would they be better in the data folder if they edit the ini?


The main reason is that it saves mod authors from having to write separate instructions for each mod manager, thus reducing user confusion.

Another reason is that once you've set it up correctly using merged.txt, there's no reason to fiddle with it anymore, and if for some reason you need to run the command again, you can just execute merged.txt.

Plus, It also separates mods that need to run every time you start the game from those that need to be run manually.

**Comment by IDCs** [comment]
@Rando456, as you probably know MO2 is limited to the 'Data' folder which is probably why some mod authors are trying to develop anti-patterns in an attempt to make their modding environment more viable. That being said - all these new patterns that are emerging will be replaced once the official modding support kit is released. (similar patterns emerged for FO4 and Skyrim in the past)

Although I understand and respect the effort that our community is dedicating to find ways to mod the game efficiently, I'm reluctant to modify the current extension logic, which is based on known Creation Engine patterns. I'm going to leave this ticket open for the time being and will review it over time.

**Comment by v2sCollections** [comment]
Yeah that makes sense but I think that is the plan here to have all mod authors use the root folder as vortex is much much more popular than mo2 and more authors are already using the root folder.

**Comment by insomnious** [comment]
If you would like to discuss further, I'd like to suggest using the forums or the vortex-starfield channel on discord. It's been a great discussion to have but I am going to close this as an issue.
