### ISSUE TITLE
sPhotoModeFolder=Photos doesn't show images

### ISSUE THREAD

**Issue by clshortfuse** [Nexus-Mods/game-starfield#29]
When using `sPhotoModeFolder=Photos` as the recommended ini fix, the photo gallery will not load images, nor will Photo Mode take pictures.

Using `sPhotoModeFolder=Data\textures\Photos` solves the issue.

This is running without any mods on the Steam version of Starfield v1.8.86.

**Comment by Pickysaurus** [comment]
This is because you route it to My Games\Starfield\Photos

**Comment by clshortfuse** [comment]
Maybe you didn't understand. I didn't route it. Vortex (this mod)did. Vortex sets:

```
sPhotoModeFolder=Photos
```

**Comment by clshortfuse** [comment]
https://github.com/Nexus-Mods/game-starfield/blob/60f897536b313697610f7609cdd602bc19eea236/src/tests.ts#L84

**Comment by Pickysaurus** [comment]
Yes, you say you're looking at "Data\textures\Photos" but you need to look at "My Games\Starfield\Photos"

**Comment by clshortfuse** [comment]
No photos appear in the gallery in game and nothing is created. This is
without mods. Maybe v1.8.86 changed something.
