### ISSUE TITLE
Utilities are not installed properly

### ISSUE THREAD

**Issue by bilago** [Nexus-Mods/game-starfield#3]
I have a INI Configuration Tool hosted on Nexus Mods. When users install it via Vortex, it places the .dll libraries in a different directory than the .exe causing the application to not work.

What can we do to avoid this issue other than disabling vortex downloads?

**Comment by HugKitten** [comment]
Starfield Upscaler also has this problem.

**Comment by HugKitten** [comment]
Setting things to engine injecting or ENB doesn't put it in the root file either. :(

**Comment by Pickysaurus** [comment]
Try it on the 0.3.0 release. If it doesn't work please include specific links to the mods you're having problems with.
