### ISSUE TITLE
Game update broke our sPhotoModeFolder in StarfieldCustom.ini tweak

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/game-starfield#36]
At some point, Bethesda updated the game to use a hard coded path to the display entries in the Photo Gallery. So even though photos are being saved to the folder that is set using `sPhotoModeFolder`, they aren't read back to display. The photo count is correct, it will display 5 placeholders, but with no actual image content.

**Comment by IDCs** [comment]
https://github.com/Nexus-Mods/game-starfield/pull/37

**Comment by insomnious** [comment]
Fixed in Vortex Starfield 0.6.7
