### ISSUE TITLE
.toml CCR scripts being installed at game's root instead of Data when using FOMOD

### ISSUE THREAD

**Issue by CansecoDev** [Nexus-Mods/game-starfield#7]
## Description:

Installing a structurally correct mod that uses FOMOD and needs as destination path something like `SFSE\Plugins\ConsoleCommandRunner\Script.toml` will end up installing the scripts at `%GameRoot%\SFSE\Plugins\ConsoleCommandRunner\Script.toml` instead of `%GameRoot%\Data\SFSE\Plugins\ConsoleCommandRunner\Script.toml`

## Expected behavior:

Installing a structurally correct mod that uses FOMOD and needs as destination path something like `SFSE\Plugins\ConsoleCommandRunner\Script.toml` should end up at `%GameRoot%\Data\SFSE\Plugins\ConsoleCommandRunner\Script.toml`

## Reproduction steps:

Download a CCR script (see links below) that  uses FOMOD and install it using Vortex.

## Links and references:

- [CCR](https://www.nexusmods.com/starfield/mods/2740)
- [Damage Overhaul - v0.2.3.2](https://www.nexusmods.com/starfield/mods/65?tab=files&file_id=8134)

**Comment by CansecoDev** [comment]
This can be worked around by setting an extra previous step on the installer to make the user select which mod manager is using, but this essentially doubles the work we have to do on patterns so is not ideal.

I've been reported that this is not a specific issue with .toml but with how Vortex handles FOMOD overall.

**Comment by Pickysaurus** [comment]
Ugh, FOMODs suck so bad. Thanks for the report.

**Comment by Pickysaurus** [comment]
For now, the FOMOD needs to be updated so that it contains the correct paths.
